"""Stubs for `picographics`, the drawing surface behind `presto.display`.

Only the display modes and pen types the Presto firmware builds are listed.
https://github.com/pimoroni/pimoroni-pico/blob/main/micropython/modules/picographics/README.md
"""

DISPLAY_PRESTO: int  # 240x240, upscaled to the panel
DISPLAY_PRESTO_FULL_RES: int  # 480x480

PEN_1BIT: int
PEN_P4: int
PEN_P8: int
PEN_RGB332: int
PEN_RGB565: int
PEN_RGB888: int

class PicoGraphics:
    def __init__(
        self,
        display: int,
        buffer: memoryview | bytearray | None = None,
        pen_type: int | None = None,
        layers: int = 1,
        rotate: int = 0,
    ) -> None: ...

    # -- state ---------------------------------------------------------------
    def get_bounds(self) -> tuple[int, int]:
        """(width, height)."""

    def get_buffer_size(self) -> int: ...
    def set_layer(self, layer: int) -> None: ...
    def set_clip(self, x: int, y: int, w: int, h: int) -> None: ...
    def get_clip(self) -> tuple[int, int, int, int]: ...
    def remove_clip(self) -> None: ...
    def set_framebuffer(self, buffer: memoryview | bytearray | None) -> None: ...
    def set_backlight(self, brightness: float) -> None: ...
    def set_blocking(self, blocking: bool) -> None: ...
    def set_update_speed(self, speed: int) -> None: ...
    def is_busy(self) -> bool: ...
    def update(self) -> None: ...
    def partial_update(self, x: int, y: int, w: int, h: int) -> None: ...

    # -- pens ----------------------------------------------------------------
    def create_pen(self, r: int, g: int, b: int) -> int: ...
    def create_pen_hsv(self, h: float, s: float, v: float) -> int: ...
    def set_pen(self, pen: int) -> None: ...
    def update_pen(self, index: int, r: int, g: int, b: int) -> int: ...
    def reset_pen(self, index: int) -> None: ...
    def set_palette(self, palette: list[int]) -> None: ...

    # -- drawing -------------------------------------------------------------
    def clear(self) -> None: ...
    def pixel(self, x: int, y: int) -> None: ...
    def pixel_span(self, x: int, y: int, length: int) -> None: ...
    def rectangle(self, x: int, y: int, w: int, h: int) -> None: ...
    def circle(self, x: int, y: int, radius: int) -> None: ...
    def line(self, x1: int, y1: int, x2: int, y2: int, thickness: int = 1) -> None: ...
    def triangle(
        self, x1: int, y1: int, x2: int, y2: int, x3: int, y3: int
    ) -> None: ...
    def polygon(self, *points: tuple[int, int]) -> None: ...
    def set_thickness(self, thickness: int) -> None: ...

    # -- text ----------------------------------------------------------------
    def set_font(self, font: str) -> None:
        """"bitmap6"/"bitmap8"/"bitmap14_outline", or a vector font name."""

    def text(
        self,
        text: str,
        x: int,
        y: int,
        wordwrap: int = -1,
        scale: float = 2,
        angle: int = 0,
        spacing: int = 1,
        fixed_width: bool = False,
    ) -> None: ...
    def measure_text(
        self, text: str, scale: float = 2, spacing: int = 1, fixed_width: bool = False
    ) -> int:
        """Width in pixels. Bitmap fonts are 8 * scale pixels tall."""

    def character(self, char: int, x: int, y: int, scale: int = 2) -> None: ...

    # -- sprites -------------------------------------------------------------
    def load_spritesheet(self, filename: str) -> None: ...
    def set_spritesheet(self, buffer: memoryview | bytearray) -> None: ...
    def sprite(
        self, sprite_x: int, sprite_y: int, x: int, y: int, scale: int = 1, transparent: int = 0
    ) -> None: ...

def RGB332_to_RGB(pen: int) -> tuple[int, int, int]: ...
def RGB565_to_RGB(pen: int) -> tuple[int, int, int]: ...
def RGB_to_RGB332(r: int, g: int, b: int) -> int: ...
def RGB_to_RGB565(r: int, g: int, b: int) -> int: ...
