"""Stubs for `picovector`, the anti-aliased vector/text renderer.

https://github.com/pimoroni/presto/blob/main/docs/picovector.md
"""

from typing import Any

from picographics import PicoGraphics

ANTIALIAS_NONE: int
ANTIALIAS_X4: int
ANTIALIAS_X16: int
ANTIALIAS_FAST: int  # alias of ANTIALIAS_X4
ANTIALIAS_BEST: int  # alias of ANTIALIAS_X16

HALIGN_LEFT: int
HALIGN_CENTER: int
HALIGN_RIGHT: int
VALIGN_TOP: int
VALIGN_MIDDLE: int
VALIGN_BOTTOM: int

class Transform:
    def rotate(self, angle: float, origin: tuple[float, float]) -> None: ...
    def translate(self, x: float, y: float) -> None: ...
    def scale(self, scale_x: float, scale_y: float) -> None: ...
    def matrix(self, matrix: list[float]) -> None: ...
    def reset(self) -> None: ...

class Polygon:
    def __init__(self) -> None: ...
    def path(self, *points: tuple[float, float]) -> None: ...
    def line(self, x1: float, y1: float, x2: float, y2: float, thickness: float) -> None: ...
    def rectangle(
        self,
        x: float,
        y: float,
        w: float,
        h: float,
        corners: tuple[float, float, float, float] | None = None,
        stroke: float = 0,
    ) -> None: ...
    def regular(self, x: float, y: float, radius: float, sides: int, stroke: float = 0) -> None: ...
    def circle(self, x: float, y: float, radius: float, stroke: float = 0) -> None: ...
    def arc(
        self, x: float, y: float, radius: float, from_: float, to: float, stroke: float = 0
    ) -> None: ...
    def star(
        self, x: float, y: float, points: int, inner_radius: float, outer_radius: float,
        stroke: float = 0,
    ) -> None: ...
    def centroid(self) -> tuple[float, float]: ...
    def bounds(self) -> tuple[float, float, float, float]: ...
    def transform(self, transform: Transform) -> Any: ...

class PicoVector:
    def __init__(self, display: PicoGraphics) -> None: ...
    def set_antialiasing(self, antialiasing: int) -> None: ...
    def set_transform(self, transform: Transform | None) -> None: ...
    def get_transform(self) -> Transform: ...
    def set_clip(self, x: int, y: int, w: int, h: int) -> None: ...
    def draw(self, *polygons: Polygon) -> None: ...
    def set_font(self, font: str, size: int) -> bool:
        """An Alright Fonts .af file that must be present on the device."""

    def set_font_size(self, size: int) -> None: ...
    def set_font_word_spacing(self, spacing: int) -> None: ...
    def set_font_letter_spacing(self, spacing: int) -> None: ...
    def set_font_line_height(self, height: int) -> None: ...
    def set_font_align(self, align: int) -> None: ...
    def measure_text(
        self, text: str, x: float = 0, y: float = 0, angle: float | None = None
    ) -> tuple[float, float, float, float]:
        """(x, y, width, height) in pixels."""

    def text(
        self,
        text: str,
        x: float,
        y: float,
        angle: float | None = None,
        max_width: int = 0,
        max_height: int = 0,
    ) -> None:
        """y is the text baseline, not its top."""
