"""Stub for MicroPython's `time`, which is not quite CPython's.

The Presto firmware's `time` adds the `ticks_*` family - millisecond counters
that wrap, and must be compared with `ticks_diff` rather than subtraction -
and drops most of CPython's calendar formatting.

This shadows the standard library for the whole workspace, which is what
lets `time.ticks_ms()` in device/ type check. The cost is that host-side
code under pc/ and tests/ sees this surface too: a CPython-only function
like `perf_counter` will look unknown until it is added here. Mirrors the
`time` stub from micropython-rp2-rpi_pico2_w-stubs (MicroPython v1.29).
"""

from typing import Tuple

_TimeTuple = Tuple[int, int, int, int, int, int, int, int]

# Opaque counter values - they wrap, so only ticks_diff/ticks_add are
# meaningful on them.
def ticks_ms() -> int: ...
def ticks_us() -> int: ...
def ticks_cpu() -> int: ...
def ticks_add(ticks: int, delta: int, /) -> int: ...
def ticks_diff(ticks1: int, ticks2: int, /) -> int:
    """Signed difference, correct across a counter wrap."""

def sleep(seconds: float, /) -> None: ...
def sleep_ms(ms: int, /) -> None: ...
def sleep_us(us: int, /) -> None: ...
def time() -> int: ...
def time_ns() -> int: ...
def localtime(secs: int | None = None, /) -> _TimeTuple: ...
def gmtime(secs: int | None = None, /) -> _TimeTuple: ...
def mktime(local_time: _TimeTuple, /) -> int: ...
